---
- name: Install dependencies
  apt: pkg=$item state=installed update_cache=yes
  with_items:
    - git
    - build-essential
    - python
    - subversion
    - wget
    - pkg-config
    - gtk+-2.0
    - libnss3
    - libnss3-dev
    - libasound2-dev
    - libpulse-dev

- name: Build libjingle
  shell: GYP_DEFINES="libjingle_java=1 build_with_libjingle=1 build_with_chromium=0 target_arch=x64 java_home=$JAVA_HOME" gclient runhooks --force 
