---
- name: Install dependencies
  apt: pkg=$item state=installed update_cache=yes
  with_items:
    - git
    - build-essential
    - python
    - subversion
    - wget
    - pkg-config
    - gtk+-2.0
    - libnss3
    - libnss3-dev
    - libasound2-dev
    - libpulse-dev

  #- command: gclient config --name trunk 'git+https://chromium.googlesource.com/external/webrtc' chdir={{ webrtc_src }}
  - command: gclient config --name trunk '{{ webrtc_repo }}' chdir={{ webrtc_src }}
  - command: gclient sync -j200 chdir={{ webrtc_src }}/trunk
  - command: git svn init --prefix=origin/ {{ webrtc_svn_repo }} -Ttrunk --rewrite-root={{ webrtc_svn_repo }} chdir={{ webrtc_src }}/trunk
  - command: git config svn-remote.svn.fetch trunk:refs/remotes/origin/master chdir={{ webrtc_src }}/trunk
  - command: git svn fetch chdir={{ webrtc_src }}/trunk
  - command: git checkout master chdir={{ webrtc_src }}/trunk
  - command: git branch -vv chdir={{ webrtc_src }}/trunk

#- name: Build libjingle
#  shell: GYP_DEFINES="libjingle_java=1 build_with_libjingle=1 build_with_chromium=0 target_arch=x64 java_home=$JAVA_HOME" gclient runhooks --force 
