---
- name: Install dependencies
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
    - git
    - git-svn
    - build-essential
    - python
    - subversion
    - wget
    - pkg-config
    - libgtk2.0-dev
    - libxtst-dev
    - libxss-dev
    - libudev-dev
    - libgcrypt11-dev
    - libpci-dev
    - libxtst-dev
    - libgnome-keyring-dev
    - libdrm-dev
    - libudev-dev
    - libnss3
    - libgconf2-dev
    - libnss3-dev
    - libasound2-dev
    - libpulse-dev

- file: path={{ webrtc_src }} state=directory

- command: gclient config --name trunk '{{ webrtc_repo }}' chdir={{ webrtc_src }}
  environment: path_env

- command: gclient sync -j200 chdir={{ webrtc_src }}
  environment: path_env

- name: Build libjingle
  shell: GYP_DEFINES="libjingle_java=1 build_with_libjingle=1 build_with_chromium=0 target_arch=x64" gclient runhooks --force chdir={{ webrtc_src }}
  environment: path_env

- name: Build jar
  shell: ninja -C out/Debug libjingle_peerconnection_jar chdir={{ webrtc_src }}/trunk
  environment: path_env
